#!/usr/bin/env node
/**
 * Generates the owner-local TypeScript adapter for the iam/v1 contract family.
 *
 * The schema is the single source: types, known-property projection and known
 * constants are all derived from contracts/iam/v1/org-zone-binding.schema.json,
 * never hand-copied. The generated module embeds nothing but an import of the
 * schema and compiles it once with the repo's existing ajv (^8.18.0, 2020-12
 * entry). Moss does not consume its own definitions through sudostack — that
 * would be a Moss -> sudostack -> Moss cycle.
 *
 *   node contracts/generate/gen-adapter.mjs          derive, write, report
 *   node contracts/generate/gen-adapter.mjs --check  derive and fail on drift
 *
 * Conformance is held honest by tests reading the shared fixtures; this script
 * only guarantees the adapter matches the schema it was generated from.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..', '..')
const CHECK = process.argv.includes('--check')

const SCHEMA_REL = 'contracts/iam/v1/org-zone-binding.schema.json'
const OUT_REL = 'src/server/zones/generated/org-zone-binding.gen.ts'

const schema = JSON.parse(readFileSync(join(REPO, SCHEMA_REL), 'utf8'))

/** Single-quoted TS literal, matching repo style (no semicolons, single quotes). */
function tsStr(v) {
  return `'${String(v).replaceAll("'", "\\'")}'`
}

/** JSON Schema property -> TypeScript type annotation. */
function tsType(prop) {
  if ('const' in prop) return tsStr(prop.const)
  if (Array.isArray(prop.enum)) return prop.enum.map((v) => tsStr(v)).join(' | ')
  if (prop.type === 'integer') return 'number'
  if (prop.type === 'boolean') return 'boolean'
  if (prop.type === 'array') return `${tsType(prop.items)}[]`
  return 'string'
}

const required = new Set(schema.required)
const properties = Object.entries(schema.properties)

const interfaceLines = properties.map(([name, prop]) => {
  const optional = required.has(name) ? '' : '?'
  return `  ${name}${optional}: ${tsType(prop)}`
})

// Known constants for open registries are declared via `x-known-values` on the
// property, so the schema stays the only editable source.
const knownConstants = properties
  .filter(([, prop]) => Array.isArray(prop['x-known-values']))
  .map(([name, prop]) => {
    const constName = name.toUpperCase() + '_KNOWN'
    return {
      constName,
      typeName: name.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, (c) => c.toUpperCase()) + 'Known',
      values: prop['x-known-values'],
    }
  })

const ts = `// @generated by contracts/generate/gen-adapter.mjs from ${SCHEMA_REL} — do not edit.
// Regenerate with: node contracts/generate/gen-adapter.mjs
import Ajv2020 from 'ajv/dist/2020'
import schema from '../../../../${SCHEMA_REL}' with { type: 'json' }

export const API_VERSION = ${tsStr(schema.properties.api_version.const)}
export const KIND = ${tsStr(schema.properties.kind.const)}
${knownConstants
  .map((k) => `export const ${k.constName} = [${k.values.map((v) => tsStr(v)).join(', ')}] as const\nexport type ${k.typeName} = (typeof ${k.constName})[number]`)
  .join('\n')}

export interface ${schema.title} {
${interfaceLines.join('\n')}
}

const KNOWN_PROPERTIES: ReadonlyArray<string> = [${properties.map(([name]) => tsStr(name)).join(', ')}]

const ajv = new Ajv2020()
// Vendor-extension keyword carrying known values for open registries; no
// validation semantics — openness is the schema's own rule.
ajv.addKeyword('x-known-values')
const validate = ajv.compile(schema)

export type ${schema.title}ParseResult =
  | { ok: true; value: ${schema.title} }
  | { ok: false; errors: string[] }

/**
 * Parses a wire payload into the object model.
 *
 * Unknown optional fields are accepted at the wire layer (the schema keeps
 * additionalProperties true) and dropped here: the parsed value carries only
 * schema-known properties.
 */
export function safeParse(input: unknown): ${schema.title}ParseResult {
  if (!validate(input)) {
    const errors = (validate.errors ?? []).map((e) => \`\${e.instancePath} \${e.message ?? ''}\`.trim())
    return { ok: false, errors }
  }
  const src = input as Record<string, unknown>
  const value: Record<string, unknown> = {}
  for (const key of KNOWN_PROPERTIES) {
    if (key in src) value[key] = src[key]
  }
  return { ok: true, value: value as ${schema.title} }
}

export const parse = safeParse
`

const outPath = join(REPO, OUT_REL)
let existing = null
try {
  existing = readFileSync(outPath, 'utf8')
} catch {
  /* first run */
}
if (existing === ts) {
  console.log('up to date')
} else if (CHECK) {
  console.error(`stale: ${OUT_REL}`)
  console.error('Run `node contracts/generate/gen-adapter.mjs` and commit the result.')
  process.exit(1)
} else {
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, ts)
  console.log(`wrote ${OUT_REL}`)
}
