/**
 * PostgreSQL schema for moss (HA P1-2e).
 *
 * This is a FRESH-DEPLOYMENT schema — it does not migrate an existing SQLite
 * database (first-version scope per the HA plan). Every statement is idempotent
 * (IF NOT EXISTS) so a migration interrupted mid-way can simply be re-run.
 *
 * Tables are the MIGRATED-FINAL shape of the sqlite side: the sqlite
 * constructor applies many `ALTER TABLE ... ADD COLUMN` steps incrementally
 * (see DirectConnectStore's constructor); here those columns are simply part
 * of the initial CREATE TABLE, so a fresh PG database matches an old,
 * fully-migrated sqlite database column-for-column.
 *
 * Dialect translation rules applied to the sqlite DDL:
 *   - `INTEGER PRIMARY KEY AUTOINCREMENT` → `BIGINT GENERATED BY DEFAULT AS
 *     IDENTITY PRIMARY KEY` (BY DEFAULT so explicit ids still bind; inserts
 *     read the id back via `RETURNING id`).
 *   - every other `INTEGER` → `BIGINT` (sqlite INTEGER is 64-bit; epoch-ms
 *     timestamps and counters need more than PG's 32-bit INTEGER). The int8
 *     values are parsed back to JS numbers by the global typeParser(20)
 *     installed in openStoreAsync (moss's integer domain is < 2^53).
 *   - `REAL` → `DOUBLE PRECISION`.
 *   - JSON is stored as TEXT on purpose (not jsonb): the stores read/write it
 *     as strings and two sites do `LIKE '%"id"%'` containment on it, which
 *     only works on text columns.
 *
 * Versioning: `_migrations` records each applied migration. DDL runs via
 * driver.exec (one statement batch per migration, on a dedicated connection)
 * rather than inside driver.transaction — PG DDL is transactional but
 * PgDriver.exec does not join the ALS transaction context; idempotent
 * statements make a re-run after a mid-migration crash safe instead.
 */
import type { DbDriver } from './driver.js'

/** Initial full schema (all stores, migrated-final shape). */
const MIGRATION_0001_INITIAL_SCHEMA = `
-- ============ DirectConnectStore: sessions & runtime lifecycle ============

CREATE TABLE IF NOT EXISTS sessions (
  session_id TEXT PRIMARY KEY,
  transcript_session_id TEXT NOT NULL,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  scopes_json TEXT NOT NULL,
  cwd TEXT NOT NULL,
  runtime_type TEXT NOT NULL,
  docker_image TEXT,
  docker_mode TEXT,
  config_dir TEXT,
  container_name TEXT,
  status TEXT NOT NULL,
  desired_state TEXT NOT NULL,
  current_attempt_id TEXT,
  transcript_path TEXT NOT NULL,
  title TEXT,
  summary TEXT,
  assistant_name TEXT,
  source TEXT,
  channel_chat_id TEXT,
  client_metadata TEXT,
  created_at BIGINT NOT NULL,
  last_active_at BIGINT NOT NULL,
  ended_at BIGINT,
  deleted_at BIGINT
);

CREATE TABLE IF NOT EXISTS session_attempts (
  attempt_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(session_id),
  generation BIGINT NOT NULL,
  backend_type TEXT NOT NULL,
  runtime_state TEXT NOT NULL,
  server_instance_id TEXT,
  runner_pid BIGINT,
  container_name TEXT,
  attach_path TEXT,
  resume_transcript_session_id TEXT NOT NULL,
  started_at BIGINT NOT NULL,
  last_heartbeat_at BIGINT,
  stopped_at BIGINT,
  exit_code BIGINT,
  exit_signal TEXT,
  stop_reason TEXT,
  error_text TEXT,
  UNIQUE (session_id, generation)
);

CREATE TABLE IF NOT EXISTS server_instances (
  instance_id TEXT PRIMARY KEY,
  host TEXT NOT NULL,
  pid BIGINT,
  started_at BIGINT NOT NULL,
  heartbeat_at BIGINT NOT NULL,
  stopped_at BIGINT,
  status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session_events (
  event_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(session_id),
  attempt_id TEXT,
  event_type TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user_idx
  ON sessions (org_id, user_id, last_active_at DESC);
CREATE INDEX IF NOT EXISTS sessions_state_idx
  ON sessions (org_id, status, last_active_at DESC);
CREATE INDEX IF NOT EXISTS attempts_session_idx
  ON session_attempts (session_id, generation DESC);
CREATE INDEX IF NOT EXISTS sessions_source_chat
  ON sessions (source, channel_chat_id, last_active_at DESC);

CREATE TABLE IF NOT EXISTS enterprises (
  id TEXT PRIMARY KEY DEFAULT 'default',
  logo TEXT,
  app_name TEXT,
  top_name TEXT,
  about_name TEXT,
  app_company_name TEXT,
  login_desp TEXT,
  client_cron_enabled BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- ============ DirectConnectStore: channels ============

CREATE TABLE IF NOT EXISTS channel_plugins (
  id TEXT NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 0,
  credentials_json TEXT,
  config_json TEXT,
  status TEXT NOT NULL,
  last_connected BIGINT,
  user_id TEXT NOT NULL,
  org_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id, user_id)
);

CREATE TABLE IF NOT EXISTS channel_users (
  id TEXT PRIMARY KEY,
  platform_user_id TEXT NOT NULL,
  platform_type TEXT NOT NULL,
  plugin_scope TEXT NOT NULL DEFAULT '',
  display_name TEXT,
  authorized_at BIGINT NOT NULL,
  last_active BIGINT,
  session_id TEXT,
  org_id TEXT,
  user_id TEXT,
  UNIQUE(platform_user_id, plugin_scope, user_id)
);

CREATE TABLE IF NOT EXISTS channel_sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  agent_type TEXT NOT NULL,
  conversation_id TEXT,
  workspace TEXT,
  chat_id TEXT,
  turn_count BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  last_activity BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS channel_pairing_requests (
  code TEXT PRIMARY KEY,
  platform_user_id TEXT NOT NULL,
  platform_type TEXT NOT NULL,
  plugin_scope TEXT,
  display_name TEXT,
  requested_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  status TEXT NOT NULL,
  user_id TEXT
);

-- ============ DirectConnectStore: tenant skills & assistants ============

CREATE TABLE IF NOT EXISTS tenant_skills (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  display_name TEXT,
  description TEXT,
  version TEXT,
  author_id TEXT NOT NULL,
  author_name TEXT,
  status TEXT DEFAULT 'pending',
  source_url TEXT,
  checksum TEXT,
  file_path TEXT,
  publish_note TEXT,
  review_note TEXT,
  reviewed_by TEXT,
  reviewed_at BIGINT,
  enabled BIGINT DEFAULT 1,
  visible_to TEXT,
  org_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_skills_author ON tenant_skills (author_id);
CREATE INDEX IF NOT EXISTS idx_tenant_skills_status ON tenant_skills (status);

CREATE TABLE IF NOT EXISTS tenant_assistants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  display_name TEXT,
  description TEXT,
  default_init_prompt TEXT,
  prompts_i18n TEXT,
  categories TEXT,
  avatar TEXT,
  emoji TEXT,
  version TEXT,
  author_id TEXT NOT NULL,
  author_name TEXT,
  status TEXT DEFAULT 'pending',
  source_url TEXT,
  checksum TEXT,
  file_path TEXT,
  enabled_skills TEXT,
  skills TEXT,
  memory_mode TEXT DEFAULT 'session',
  agent_type TEXT DEFAULT 'chat',
  publish_note TEXT,
  review_note TEXT,
  reviewed_by TEXT,
  reviewed_at BIGINT,
  enabled BIGINT DEFAULT 1,
  visible_to TEXT,
  enabled_wikis TEXT,
  enabled_corp_apps TEXT,
  workflow TEXT,
  org_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_assistants_author ON tenant_assistants (author_id);
CREATE INDEX IF NOT EXISTS idx_tenant_assistants_status ON tenant_assistants (status);

-- ============ DirectConnectStore: document center (v2 final shape) ============

CREATE TABLE IF NOT EXISTS document_tree_nodes (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  parent_id TEXT REFERENCES document_tree_nodes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  source_id TEXT,
  source_path TEXT,
  auto_managed BIGINT DEFAULT 0,
  alias TEXT,
  last_synced_at BIGINT,
  deleted_at BIGINT
);
CREATE INDEX IF NOT EXISTS document_tree_nodes_parent_idx
  ON document_tree_nodes (parent_id);
CREATE INDEX IF NOT EXISTS document_tree_nodes_org_idx
  ON document_tree_nodes (org_id, sort_order);
CREATE INDEX IF NOT EXISTS document_tree_nodes_source_idx
  ON document_tree_nodes (source_id, source_path);

CREATE TABLE IF NOT EXISTS documents (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  node_id TEXT NOT NULL REFERENCES document_tree_nodes(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  storage_path TEXT NOT NULL,
  uploaded_by TEXT NOT NULL,
  uploaded_at BIGINT NOT NULL,
  source_id TEXT,
  external_id TEXT,
  external_etag TEXT,
  content_sha256 TEXT,
  deleted_at BIGINT
);
CREATE INDEX IF NOT EXISTS documents_node_idx ON documents (node_id);
CREATE INDEX IF NOT EXISTS documents_org_idx  ON documents (org_id);
CREATE INDEX IF NOT EXISTS documents_sha_idx  ON documents (org_id, content_sha256);
CREATE INDEX IF NOT EXISTS documents_external_idx ON documents (source_id, external_id);

CREATE TABLE IF NOT EXISTS wikis (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  node_id TEXT REFERENCES document_tree_nodes(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  storage_path TEXT NOT NULL,
  build_status TEXT NOT NULL DEFAULT 'pending',
  source_document_ids TEXT NOT NULL DEFAULT '[]',
  last_built_at BIGINT,
  last_build_error TEXT,
  source_mode TEXT NOT NULL DEFAULT 'files',
  source_node_id TEXT,
  source_node_ids TEXT NOT NULL DEFAULT '[]',
  source_exclude_node_ids TEXT NOT NULL DEFAULT '[]',
  auto_rebuild BIGINT NOT NULL DEFAULT 0,
  needs_rebuild BIGINT DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS wikis_org_idx  ON wikis (org_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS wikis_node_idx ON wikis (node_id);

CREATE TABLE IF NOT EXISTS wiki_build_jobs (
  id TEXT PRIMARY KEY,
  wiki_id TEXT NOT NULL REFERENCES wikis(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued',
  progress BIGINT NOT NULL DEFAULT 0,
  current_step TEXT,
  error_message TEXT,
  session_id TEXT,
  triggered_by TEXT NOT NULL,
  queued_at BIGINT NOT NULL,
  started_at BIGINT,
  finished_at BIGINT
);
CREATE INDEX IF NOT EXISTS wiki_build_jobs_wiki_idx
  ON wiki_build_jobs (wiki_id, queued_at DESC);
CREATE INDEX IF NOT EXISTS wiki_build_jobs_status_idx
  ON wiki_build_jobs (status, queued_at);

CREATE TABLE IF NOT EXISTS external_sources (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  config_json TEXT NOT NULL,
  credentials_secret_key TEXT,
  sync_interval_sec BIGINT NOT NULL DEFAULT 3600,
  auto_build_enabled BIGINT NOT NULL DEFAULT 0,
  enabled BIGINT NOT NULL DEFAULT 1,
  last_sync_at BIGINT,
  last_sync_status TEXT,
  last_sync_error TEXT,
  created_by TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS external_sources_org_idx
  ON external_sources (org_id);
CREATE INDEX IF NOT EXISTS external_sources_enabled_idx
  ON external_sources (enabled, last_sync_at);

-- ============ DirectConnectStore: corp apps & inbound buffer ============

CREATE TABLE IF NOT EXISTS corp_apps (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  app_key TEXT NOT NULL,
  config_json TEXT NOT NULL,
  credentials_secret_key TEXT,
  enabled BIGINT NOT NULL DEFAULT 1,
  created_by TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS corp_apps_org_name_idx
  ON corp_apps (org_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS corp_apps_org_type_key_idx
  ON corp_apps (org_id, type, app_key);
CREATE INDEX IF NOT EXISTS corp_apps_org_idx ON corp_apps (org_id);

CREATE TABLE IF NOT EXISTS corp_app_inbound (
  id TEXT PRIMARY KEY,
  corp_app_id TEXT NOT NULL,
  org_id TEXT NOT NULL,
  seq BIGINT NOT NULL,
  from_user TEXT,
  msg_type TEXT,
  text TEXT,
  media_id TEXT,
  file_name TEXT,
  received_at BIGINT NOT NULL,
  payload_json TEXT
);
-- Per-app monotonic poll cursor. On PG READ COMMITTED the single-statement
-- MAX(seq)+1 insert still races under concurrent LB callbacks; this unique
-- index is the hard backstop and appendCorpAppInbound retries on 23505.
CREATE UNIQUE INDEX IF NOT EXISTS corp_app_inbound_seq_uniq
  ON corp_app_inbound (corp_app_id, seq);

-- ============ DirectConnectStore: secrets management ============

CREATE TABLE IF NOT EXISTS config_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  pinyin TEXT,
  scope TEXT NOT NULL DEFAULT 'system',
  url_pattern TEXT,
  scheme TEXT,
  bearer_prefix TEXT,
  status BIGINT DEFAULT 1,
  org_id TEXT,
  auth_type TEXT,
  auth_url TEXT,
  token_url TEXT,
  client_id TEXT,
  client_secret_key TEXT,
  refresh_token_key TEXT,
  default_scopes TEXT,
  token_request_json TEXT,
  mint_script TEXT,
  body_auth_check TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_config_items_scope_status
  ON config_items (scope, status);
CREATE INDEX IF NOT EXISTS idx_config_items_status
  ON config_items (status);
CREATE INDEX IF NOT EXISTS idx_config_items_org
  ON config_items (org_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_config_items_org_pinyin
  ON config_items (org_id, pinyin) WHERE scope != 'user';
CREATE UNIQUE INDEX IF NOT EXISTS uniq_config_items_org_name
  ON config_items (org_id, name) WHERE scope != 'user';
CREATE UNIQUE INDEX IF NOT EXISTS uniq_config_items_user_pinyin
  ON config_items (pinyin) WHERE scope = 'user';
CREATE UNIQUE INDEX IF NOT EXISTS uniq_config_items_user_name
  ON config_items (name) WHERE scope = 'user';

CREATE TABLE IF NOT EXISTS config_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_item_id BIGINT NOT NULL,
  config_key TEXT NOT NULL,
  name TEXT NOT NULL,
  config_desc TEXT,
  required BIGINT DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  FOREIGN KEY (config_item_id) REFERENCES config_items(id) ON DELETE CASCADE,
  UNIQUE(config_item_id, config_key)
);
CREATE INDEX IF NOT EXISTS idx_config_entries_item
  ON config_entries (config_item_id);

CREATE TABLE IF NOT EXISTS secret_metadata (
  id TEXT PRIMARY KEY,
  config_item_id BIGINT NOT NULL UNIQUE,
  org_id TEXT,
  expires_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  FOREIGN KEY (config_item_id) REFERENCES config_items(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_secret_metadata_expires
  ON secret_metadata (expires_at);

CREATE TABLE IF NOT EXISTS department_secret_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id TEXT NOT NULL,
  config_item_id BIGINT NOT NULL,
  org_id TEXT,
  created_at BIGINT NOT NULL,
  FOREIGN KEY (config_item_id) REFERENCES config_items(id) ON DELETE CASCADE,
  UNIQUE(department_id, config_item_id)
);
CREATE INDEX IF NOT EXISTS idx_dept_policies_dept
  ON department_secret_policies (department_id);
CREATE INDEX IF NOT EXISTS idx_dept_policies_config
  ON department_secret_policies (config_item_id);

CREATE TABLE IF NOT EXISTS secret_audit_log (
  id TEXT PRIMARY KEY,
  actor_id TEXT NOT NULL,
  actor_name TEXT,
  action TEXT NOT NULL,
  config_item_id BIGINT,
  org_id TEXT,
  namespace TEXT NOT NULL,
  key TEXT NOT NULL,
  detail TEXT,
  ip_address TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created
  ON secret_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_actor_time
  ON secret_audit_log (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_config_item_time
  ON secret_audit_log (config_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action_time
  ON secret_audit_log (action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_namespace
  ON secret_audit_log (namespace, key);

-- ============ DirectConnectStore: cron & event triggers ============

CREATE TABLE IF NOT EXISTS cron_jobs (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  co_owner_ids TEXT,
  executor_user_id TEXT,
  name TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 1,
  deleted_at BIGINT,
  schedule_kind TEXT NOT NULL,
  schedule_value TEXT NOT NULL,
  schedule_tz TEXT,
  schedule_description TEXT,
  payload_message TEXT NOT NULL,
  conversation_mode TEXT NOT NULL,
  bound_session_id TEXT,
  last_session_id TEXT,
  assistant_id TEXT,
  assistant_name TEXT,
  workspace TEXT,
  runtime_json TEXT,
  next_run_at BIGINT,
  lease_until BIGINT,
  last_run_at BIGINT,
  last_status TEXT,
  last_error TEXT,
  run_count BIGINT DEFAULT 0,
  retry_count BIGINT DEFAULT 0,
  max_retries BIGINT DEFAULT 3,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cron_jobs_org_user
  ON cron_jobs (org_id, user_id);
CREATE INDEX IF NOT EXISTS idx_cron_jobs_next_run
  ON cron_jobs (next_run_at) WHERE enabled = 1 AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_cron_jobs_lease
  ON cron_jobs (lease_until) WHERE enabled = 1 AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_cron_jobs_bound_session
  ON cron_jobs (bound_session_id);
CREATE INDEX IF NOT EXISTS idx_cron_jobs_last_session
  ON cron_jobs (last_session_id);

CREATE TABLE IF NOT EXISTS cron_job_runs (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  session_id TEXT,
  status TEXT NOT NULL,
  started_at BIGINT,
  finished_at BIGINT,
  error TEXT,
  summary TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cron_job_runs_job
  ON cron_job_runs (job_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cron_job_runs_session
  ON cron_job_runs (session_id);

CREATE TABLE IF NOT EXISTS event_triggers (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 1,
  deleted_at BIGINT,
  secret_hash TEXT NOT NULL,
  secret_prefix TEXT NOT NULL,
  prompt_template TEXT NOT NULL,
  assistant_name TEXT,
  conversation_mode TEXT NOT NULL DEFAULT 'new',
  bound_session_id TEXT,
  last_session_id TEXT,
  workspace TEXT,
  timeout_ms BIGINT,
  rate_limit_per_min BIGINT,
  last_used_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_event_triggers_org
  ON event_triggers (org_id, deleted_at);

CREATE TABLE IF NOT EXISTS event_trigger_runs (
  id TEXT PRIMARY KEY,
  trigger_id TEXT NOT NULL,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  session_id TEXT,
  status TEXT NOT NULL,
  payload_json TEXT,
  idempotency_key TEXT,
  started_at BIGINT,
  finished_at BIGINT,
  error TEXT,
  summary TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_event_trigger_runs_trigger
  ON event_trigger_runs (trigger_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_event_trigger_runs_status
  ON event_trigger_runs (status, created_at);
CREATE INDEX IF NOT EXISTS idx_event_trigger_runs_session
  ON event_trigger_runs (session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_trigger_runs_idem
  ON event_trigger_runs (trigger_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ============ AuthCenterDb (migrated-final shape) ============

CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  ext_org_id TEXT,
  created_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS organizations_ext_uniq
  ON organizations (ext_org_id) WHERE ext_org_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS departments (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id),
  parent_id TEXT REFERENCES departments(id),
  name TEXT NOT NULL,
  ext_dept_id TEXT,
  token_limit BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS departments_org_idx ON departments (org_id);
CREATE INDEX IF NOT EXISTS departments_parent_idx ON departments (parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS departments_ext_uniq
  ON departments (org_id, ext_dept_id) WHERE ext_dept_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id),
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  display_name TEXT,
  department_id TEXT REFERENCES departments(id),
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  password_hash TEXT,
  password_updated_at BIGINT,
  last_login_at BIGINT,
  local_auth BIGINT NOT NULL DEFAULT 0,
  ext_user_id TEXT,
  token_limit BIGINT,
  phone TEXT,
  sudorouter_user_id TEXT,
  sudorouter_key TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS users_org_idx ON users (org_id);
CREATE INDEX IF NOT EXISTS users_email_idx ON users (email);
CREATE INDEX IF NOT EXISTS users_department_idx ON users (department_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_ext_uniq
  ON users (org_id, ext_user_id) WHERE ext_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_uniq
  ON users (phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS api_keys (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  prefix TEXT NOT NULL,
  secret_hash TEXT NOT NULL,
  scopes_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_at BIGINT NOT NULL,
  last_used_at BIGINT
);
CREATE INDEX IF NOT EXISTS api_keys_org_idx ON api_keys (org_id);
CREATE INDEX IF NOT EXISTS api_keys_user_idx ON api_keys (user_id);

CREATE TABLE IF NOT EXISTS revoked_tokens (
  jti TEXT PRIMARY KEY,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS revoked_tokens_expiry_idx ON revoked_tokens (expires_at);

CREATE TABLE IF NOT EXISTS oauth_provider_tokens (
  user_id TEXT PRIMARY KEY,
  token_enc TEXT NOT NULL,
  token_iv TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS oauth_provider_tokens_expiry_idx ON oauth_provider_tokens (expires_at);

CREATE TABLE IF NOT EXISTS minted_service_tokens (
  user_id TEXT NOT NULL,
  config_item_id BIGINT NOT NULL,
  token_enc TEXT NOT NULL,
  token_iv TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, config_item_id)
);
CREATE INDEX IF NOT EXISTS minted_service_tokens_expiry_idx ON minted_service_tokens (expires_at);

CREATE TABLE IF NOT EXISTS server_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS phone_login_codes (
  phone TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  attempts BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phone_login_sends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,
  sent_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS phone_login_sends_idx
  ON phone_login_sends (phone, sent_at);

CREATE TABLE IF NOT EXISTS credit_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_no TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL REFERENCES users(id),
  org_id TEXT NOT NULL,
  requested_points BIGINT NOT NULL,
  approved_points BIGINT,
  reason TEXT,
  status TEXT NOT NULL,
  admin_comment TEXT,
  created_at BIGINT NOT NULL,
  reviewed_at BIGINT,
  sudorouter_error TEXT
);
CREATE INDEX IF NOT EXISTS credit_applications_user_idx
  ON credit_applications (user_id, created_at DESC);

-- ============ McpStore (migrated-final shape) ============

CREATE TABLE IF NOT EXISTS mcp_servers (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  template_id TEXT,
  name TEXT NOT NULL,
  display_name TEXT,
  description TEXT,
  icon TEXT,
  category TEXT,
  risk_level TEXT NOT NULL DEFAULT 'low',
  responsible_person TEXT,
  scope TEXT NOT NULL,
  owner_type TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  mcp_type TEXT NOT NULL,
  url TEXT,
  command TEXT,
  args_json TEXT,
  env_json TEXT,
  timeout_ms BIGINT DEFAULT 30000,
  health_check_url TEXT,
  use_proxy BIGINT DEFAULT 0,
  auth_type TEXT DEFAULT 'none',
  secret_ref TEXT,
  auth_config_json TEXT,
  visible_to TEXT,
  bound_assistants TEXT,
  bound_skills TEXT,
  allow_read BIGINT DEFAULT 1,
  allow_write BIGINT DEFAULT 1,
  require_confirmation_for_write BIGINT DEFAULT 0,
  allow_read_sensitive_fields BIGINT DEFAULT 0,
  allow_outbound_network BIGINT DEFAULT 1,
  allow_scheduled_task BIGINT DEFAULT 0,
  audit_request BIGINT DEFAULT 0,
  audit_response_summary BIGINT DEFAULT 0,
  redact_sensitive_fields BIGINT DEFAULT 0,
  allow_user_disable BIGINT DEFAULT 1,
  status TEXT DEFAULT 'pending',
  enabled BIGINT DEFAULT 1,
  last_invocation_at BIGINT,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_org_scope ON mcp_servers(org_id, scope);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_owner ON mcp_servers(owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_org_status ON mcp_servers(org_id, status);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_created_by ON mcp_servers(created_by);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mcp_servers_org_name ON mcp_servers(org_id, name);

CREATE TABLE IF NOT EXISTS mcp_policies (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL UNIQUE,
  allow_personal_mcp BIGINT DEFAULT 0,
  allow_stdio_mcp BIGINT DEFAULT 0,
  allow_http_sse_mcp BIGINT DEFAULT 0,
  allow_local_file_access BIGINT DEFAULT 0,
  allow_external_network BIGINT DEFAULT 0,
  domain_whitelist_json TEXT,
  require_approval BIGINT DEFAULT 0,
  allow_auto_task_call_personal_mcp BIGINT DEFAULT 0,
  allow_enterprise_assistant_call_personal_mcp BIGINT DEFAULT 0,
  allow_enterprise_context_in_personal_mcp BIGINT DEFAULT 0,
  require_confirmation_for_high_risk BIGINT DEFAULT 1,
  require_confirmation_for_write BIGINT DEFAULT 1,
  audit_request_params BIGINT DEFAULT 0,
  audit_response_summary BIGINT DEFAULT 0,
  redact_audit_logs BIGINT DEFAULT 0,
  limit_concurrency_and_rate BIGINT DEFAULT 0,
  restrict_callable_models BIGINT DEFAULT 0,
  updated_by TEXT,
  created_by TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS mcp_audit_log (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  mcp_server_id TEXT REFERENCES mcp_servers(id) ON DELETE SET NULL,
  mcp_server_name TEXT,
  session_id TEXT,
  user_id TEXT NOT NULL,
  user_name TEXT,
  action TEXT NOT NULL,
  tool_name TEXT,
  request_params_json TEXT,
  response_summary TEXT,
  status TEXT,
  error_message TEXT,
  ip_address TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_org_time ON mcp_audit_log(org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_server ON mcp_audit_log(mcp_server_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_user ON mcp_audit_log(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_action ON mcp_audit_log(action, created_at DESC);

CREATE TABLE IF NOT EXISTS mcp_approval_requests (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  user_name TEXT,
  mcp_server_id TEXT NOT NULL,
  mcp_server_snapshot TEXT,
  status TEXT DEFAULT 'pending',
  reviewed_by TEXT,
  reviewer_name TEXT,
  review_note TEXT,
  reviewed_at BIGINT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mcp_approval_status ON mcp_approval_requests(org_id, status);
CREATE INDEX IF NOT EXISTS idx_mcp_approval_user ON mcp_approval_requests(user_id);

CREATE TABLE IF NOT EXISTS mcp_templates (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT NOT NULL,
  category TEXT,
  tags_json TEXT,
  mcp_type TEXT NOT NULL DEFAULT 'http',
  url TEXT,
  command TEXT,
  args_json TEXT,
  env_json TEXT,
  timeout_ms BIGINT DEFAULT 30000,
  auth_type TEXT DEFAULT 'none',
  auth_config_json TEXT DEFAULT NULL,
  scope TEXT DEFAULT 'org',
  risk_level TEXT DEFAULT 'low',
  responsible_person TEXT DEFAULT NULL,
  security_policy_json TEXT DEFAULT NULL,
  visible_to_json TEXT DEFAULT NULL,
  bound_assistants_json TEXT DEFAULT NULL,
  bound_skills_json TEXT DEFAULT NULL,
  config_json TEXT,
  downloads BIGINT DEFAULT 0,
  rating DOUBLE PRECISION DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mcp_templates_org ON mcp_templates(org_id);
CREATE INDEX IF NOT EXISTS idx_mcp_templates_category ON mcp_templates(org_id, category);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mcp_templates_org_name ON mcp_templates(org_id, name);

CREATE TABLE IF NOT EXISTS mcp_user_disabled (
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  mcp_server_id TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (org_id, user_id, mcp_server_id)
);

-- ============ CabinStore ============

CREATE TABLE IF NOT EXISTS cabin_conversations (
  id TEXT PRIMARY KEY,
  conversation_key TEXT NOT NULL UNIQUE,
  passenger_id TEXT,
  passenger_ref TEXT,
  passenger_name TEXT,
  flight_id TEXT NOT NULL,
  flight_date TEXT NOT NULL,
  seat_id TEXT,
  tablet_id TEXT NOT NULL,
  moss_session_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  summary TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cabin_conversations_passenger
  ON cabin_conversations(passenger_id, passenger_ref);
CREATE INDEX IF NOT EXISTS idx_cabin_conversations_flight
  ON cabin_conversations(flight_id, flight_date);

CREATE TABLE IF NOT EXISTS cabin_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES cabin_conversations(id),
  role TEXT NOT NULL,
  source TEXT NOT NULL,
  content TEXT NOT NULL,
  intent TEXT,
  slots_json TEXT,
  tool_calls_json TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cabin_messages_conversation_created
  ON cabin_messages(conversation_id, created_at);

CREATE TABLE IF NOT EXISTS cabin_voice_logs (
  id TEXT PRIMARY KEY,
  conversation_id TEXT,
  message_id TEXT,
  type TEXT NOT NULL,
  text TEXT,
  status TEXT NOT NULL,
  error_message TEXT,
  elapsed_ms BIGINT,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS cabin_managed_seats (
  id TEXT PRIMARY KEY,
  aircraft_no TEXT,
  flight_id TEXT NOT NULL,
  flight_date TEXT NOT NULL,
  seat_no TEXT NOT NULL,
  column_no TEXT,
  flight_seat_id TEXT,
  aircraft_seat_id TEXT,
  tablet_id TEXT,
  tablet_type TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  last_seen_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE(flight_id, flight_date, seat_no)
);
CREATE INDEX IF NOT EXISTS idx_cabin_managed_seats_flight
  ON cabin_managed_seats(flight_id, flight_date, status);
CREATE INDEX IF NOT EXISTS idx_cabin_managed_seats_aircraft
  ON cabin_managed_seats(aircraft_no, status);

CREATE TABLE IF NOT EXISTS cabin_alerts (
  id TEXT PRIMARY KEY,
  aircraft_no TEXT,
  flight_id TEXT NOT NULL,
  flight_date TEXT,
  phase_code BIGINT,
  phase_name TEXT NOT NULL,
  seat_no TEXT,
  alert_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'warning',
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  source_event_id TEXT,
  details_json TEXT,
  created_at BIGINT NOT NULL,
  resolved_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_cabin_alerts_flight_created
  ON cabin_alerts(flight_id, flight_date, created_at);

CREATE TABLE IF NOT EXISTS cabin_health_reports (
  id TEXT PRIMARY KEY,
  aircraft_no TEXT,
  flight_id TEXT NOT NULL,
  flight_date TEXT NOT NULL,
  seat_no TEXT NOT NULL,
  tablet_id TEXT,
  passenger_id TEXT,
  passenger_ref TEXT,
  status TEXT NOT NULL,
  language TEXT,
  sample_count BIGINT NOT NULL DEFAULT 0,
  samples_json TEXT,
  metrics_json TEXT,
  summary_json TEXT,
  error_code TEXT,
  error_message TEXT,
  cancelled_at BIGINT,
  started_at BIGINT NOT NULL,
  collect_until BIGINT NOT NULL,
  generated_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cabin_health_reports_seat_status
  ON cabin_health_reports(flight_id, flight_date, seat_no, status);
CREATE INDEX IF NOT EXISTS idx_cabin_health_reports_created
  ON cabin_health_reports(created_at);

-- ============ adapterService & userModelPreference ============

CREATE TABLE IF NOT EXISTS adapter_configs (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  platform TEXT NOT NULL CHECK(platform IN ('telegram', 'feishu')),
  config_json TEXT NOT NULL DEFAULT '{}',
  enabled BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS adapter_configs_user_platform_idx
  ON adapter_configs (org_id, user_id, platform);

CREATE TABLE IF NOT EXISTS user_model_preferences (
  user_id TEXT PRIMARY KEY,
  model_id TEXT NOT NULL,
  updated_at BIGINT NOT NULL
);
`

interface PgMigration {
  version: number
  name: string
  sql: string
}

const MIGRATIONS: PgMigration[] = [
  { version: 1, name: 'initial-schema', sql: MIGRATION_0001_INITIAL_SCHEMA },
]

/** Version bookkeeping table (created out-of-band; itself always idempotent). */
const MIGRATIONS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS _migrations (
  version BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at BIGINT NOT NULL
)
`

const SCHEMA_MIGRATE_LOCK_KEY = 'moss:pg-schema-migrate'
const SCHEMA_MIGRATE_LOCK_RETRY_MS = 1_000
const SCHEMA_MIGRATE_LOCK_TIMEOUT_MS = 60_000

/**
 * Bring the PG database up to the latest schema version. Safe to call on
 * every boot: applied versions are skipped, and every statement inside a
 * migration is idempotent (IF NOT EXISTS), so a crash mid-migration heals on
 * the next run by re-applying the remainder.
 *
 * Cross-instance serialization for simultaneous first boots (ha-crosshost:
 * two instances against one empty PG). tryRunExclusive is try-semantics —
 * it resolves null instead of queueing — so the loser retries on a short
 * interval; once the winner commits, `_migrations` is populated and the
 * loser's locked section reads it and skips. Concurrent bare
 * CREATE TABLE IF NOT EXISTS can hit pg_type_typname_nsp_index and the
 * INSERT can hit the _migrations PK; running one migration at a time avoids
 * both. The advisory lock is tx-scoped and releases only after fn resolves,
 * so even though `exec` rides a dedicated connection (not the locked tx),
 * the two instances' migration executions stay serialized in time.
 */
export async function applyPgSchema(driver: DbDriver): Promise<void> {
  const deadline = Date.now() + SCHEMA_MIGRATE_LOCK_TIMEOUT_MS
  for (;;) {
    const done = await driver.tryRunExclusive(SCHEMA_MIGRATE_LOCK_KEY, async () => {
      await driver.exec(MIGRATIONS_TABLE_SQL)
      const appliedRows = await driver.all<{ version: number | string }>(
        'SELECT version FROM _migrations',
      )
      const applied = new Set(appliedRows.map(r => Number(r.version)))
      for (const migration of MIGRATIONS) {
        if (applied.has(migration.version)) continue
        await driver.exec(migration.sql)
        await driver.run(
          'INSERT INTO _migrations (version, name, applied_at) VALUES (?, ?, ?)',
          [migration.version, migration.name, Date.now()],
        )
      }
    })
    // void fn: success resolves undefined, lock-not-acquired resolves null —
    // `if (!done)` would misread success as failure.
    if (done !== null) return
    if (Date.now() > deadline) {
      throw new Error(
        'pg schema migration lock timeout (another instance held the lock too long)',
      )
    }
    await new Promise(resolve => setTimeout(resolve, SCHEMA_MIGRATE_LOCK_RETRY_MS))
  }
}
