/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The underlying NexusVfsClient is already thread-safe (sync wrapper
 * around a background tokio thread). All public methods here are
 * synchronous and use napi `AsyncTask` wrappers to avoid blocking the
 * Node.js event loop.
 */
export declare class NexusGrpcClient {
  /**
   * Create a new **plaintext** gRPC client targeting the given endpoint
   * (e.g. "http://127.0.0.1:2126"). Used by the embedded/dev `serve-local`
   * daemon (trusted loopback, no TLS).
   * The TCP connection is lazy — established on first RPC call.
   */
  constructor(endpoint: string)
  /**
   * Create a new **mTLS** gRPC client targeting `endpoint`
   * (e.g. "https://127.0.0.1:8443"), authenticating with moss's client
   * identity against the cluster CA. `caPath`, `certPath`, `keyPath` are
   * filesystem paths to PEM files. `domain` optionally overrides the SNI /
   * cert-verification hostname. The TLS handshake is lazy.
   */
  static withMtls(endpoint: string, caPath: string, certPath: string, keyPath: string, domain?: string | undefined | null): NexusGrpcClient
  /**
   * Generic gRPC call: method name + JSON payload string + auth token.
   * Returns the response as a JSON string.
   */
  call(method: string, payload: string, authToken: string): string
  /**
   * Binary gRPC call: method name + raw protobuf payload + auth token.
   * Returns raw response bytes (protobuf-encoded).
   * Use this for plugin dispatch (e.g. "password-vault.secret_put") where
   * the wire format is protobuf, not JSON.
   */
  callBinary(method: string, payload: Buffer, authToken: string): Buffer
  /** Read a file from the VFS. Returns raw bytes. */
  read(path: string, authToken: string): Buffer
  /** Delete a file from the VFS. */
  delete(path: string, authToken: string): void
  /** Write raw bytes to a VFS path. */
  write(path: string, content: Buffer, authToken: string): void
  /** Delete a VFS path. */
  delete(path: string, authToken: string): void
  /** Ping the nexus gRPC server. Returns the response as a JSON string. */
  ping(authToken: string): string
}
