// This file is auto-generated by `napi build`.
// The stub below allows `require('../../native/nexus-napi')` to resolve
// before the native binary is built.

const { existsSync } = require('fs');
const { dirname, join, resolve } = require('path');

const candidateDirs = [
  // Standalone server images run from /app and place the native addon here.
  join(process.cwd(), 'native', 'nexus-napi'),
  // If launched from bin/moss-server.mjs, resolve ../native/nexus-napi.
  typeof process.argv[1] === 'string'
    ? resolve(dirname(process.argv[1]), '..', 'native', 'nexus-napi')
    : null,
  // Unbundled development/test execution.
  typeof __filename === 'string' ? dirname(__filename) : __dirname,
].filter(Boolean);

// napi-rs convention: platform-specific binary next to index.js
const candidates = [
  `nexus-napi.${process.platform}-${process.arch}.node`,
  'nexus-napi.node',
];

let nativeBinding;
let searched = [];
for (const dir of candidateDirs) {
  for (const name of candidates) {
    const path = join(dir, name);
    searched.push(path);
    if (existsSync(path)) {
      nativeBinding = require(path);
      break;
    }
  }
  if (nativeBinding) break;
}

if (!nativeBinding) {
  throw new Error(
    `Failed to load nexus-napi native module. Run \`bun run build:native\` first.\n` +
    `Looked for: ${searched.join(', ')}`
  );
}

module.exports = nativeBinding;
